before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    dir: cmd/rest
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - heamon
    image_templates:
    - "utkarsh-pro/heamon:latest"
    - "utkarsh-pro/heamon:{{ .Tag }}"
    - "utkarsh-pro/heamon:v{{ .Major }}"
    dockerfile: Dockerfile
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
